/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Civitas {
  export type IssueRecordStruct = {
    issueId: string;
    adminId: string;
    timestamp: BigNumberish;
    status: string;
    exists: boolean;
  };

  export type IssueRecordStructOutput = [
    issueId: string,
    adminId: string,
    timestamp: bigint,
    status: string,
    exists: boolean
  ] & {
    issueId: string;
    adminId: string;
    timestamp: bigint;
    status: string;
    exists: boolean;
  };
}

export interface CivitasInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "adminNames"
      | "distributeReward"
      | "getIssue"
      | "isAdmin"
      | "issues"
      | "rewards"
      | "setAdminName"
      | "verifyIssue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminNameSet"
      | "IssueVerified"
      | "RewardDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getIssue", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "issues", values: [string]): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdminName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIssue",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adminNames", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIssue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issues", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAdminName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIssue",
    data: BytesLike
  ): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [admin: AddressLike];
  export type OutputTuple = [admin: string];
  export interface OutputObject {
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminNameSetEvent {
  export type InputTuple = [admin: AddressLike, name: string];
  export type OutputTuple = [admin: string, name: string];
  export interface OutputObject {
    admin: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssueVerifiedEvent {
  export type InputTuple = [
    issueId: string,
    adminId: string,
    timestamp: BigNumberish,
    status: string
  ];
  export type OutputTuple = [
    issueId: string,
    adminId: string,
    timestamp: bigint,
    status: string
  ];
  export interface OutputObject {
    issueId: string;
    adminId: string;
    timestamp: bigint;
    status: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Civitas extends BaseContract {
  connect(runner?: ContractRunner | null): Civitas;
  waitForDeployment(): Promise<this>;

  interface: CivitasInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  adminNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  distributeReward: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getIssue: TypedContractMethod<
    [_issueId: string],
    [Civitas.IssueRecordStructOutput],
    "view"
  >;

  isAdmin: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  issues: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean] & {
        issueId: string;
        adminId: string;
        timestamp: bigint;
        status: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  rewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setAdminName: TypedContractMethod<[_name: string], [void], "nonpayable">;

  verifyIssue: TypedContractMethod<
    [_issueId: string, _adminId: string, _status: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getIssue"
  ): TypedContractMethod<
    [_issueId: string],
    [Civitas.IssueRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issues"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean] & {
        issueId: string;
        adminId: string;
        timestamp: bigint;
        status: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAdminName"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyIssue"
  ): TypedContractMethod<
    [_issueId: string, _adminId: string, _status: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminNameSet"
  ): TypedContractEvent<
    AdminNameSetEvent.InputTuple,
    AdminNameSetEvent.OutputTuple,
    AdminNameSetEvent.OutputObject
  >;
  getEvent(
    key: "IssueVerified"
  ): TypedContractEvent<
    IssueVerifiedEvent.InputTuple,
    IssueVerifiedEvent.OutputTuple,
    IssueVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminNameSet(address,string)": TypedContractEvent<
      AdminNameSetEvent.InputTuple,
      AdminNameSetEvent.OutputTuple,
      AdminNameSetEvent.OutputObject
    >;
    AdminNameSet: TypedContractEvent<
      AdminNameSetEvent.InputTuple,
      AdminNameSetEvent.OutputTuple,
      AdminNameSetEvent.OutputObject
    >;

    "IssueVerified(string,string,uint256,string)": TypedContractEvent<
      IssueVerifiedEvent.InputTuple,
      IssueVerifiedEvent.OutputTuple,
      IssueVerifiedEvent.OutputObject
    >;
    IssueVerified: TypedContractEvent<
      IssueVerifiedEvent.InputTuple,
      IssueVerifiedEvent.OutputTuple,
      IssueVerifiedEvent.OutputObject
    >;

    "RewardDistributed(address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
  };
}
